---
- name: Infoblox - Get Network record ID
  connection: local
  uri:
    url: "{{infoblox_url}}/network"
    method: GET
    force_basic_auth: yes
    user: "{{infoblox_username}}"
    password: "{{infoblox_password}}"
    body: "network={{ infoblox_network }}"
    return_content: yes
    validate_certs: no
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: infoblox_delete_id 

- name: Infoblox - Delete Network record
  connection: local
  uri:
    url: "{{infoblox_url}}/{{ infoblox_delete_id.json[0]._ref }}"
    method: DELETE
    force_basic_auth: yes
    user: "{{infoblox_username}}"
    password: "{{infoblox_password}}"
    validate_certs: no
  when: infoblox_delete_id.json is defined and (infoblox_delete_id.json|length>0)