---
- name: Infoblox - Get record ID
  connection: local
  uri:
    url: "{{infoblox_url}}/record:{{infoblox_recordtype}}"
    method: GET
    force_basic_auth: yes
    user: "{{infoblox_username}}"
    password: "{{infoblox_password}}"
    body: "name={{ infoblox_name }}"
    return_content: yes
    validate_certs: no
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: infoblox_delete_id 

- name: Infoblox - Delete record
  connection: local
  uri:
    url: "{{infoblox_url}}/{{ infoblox_delete_id.json[0]._ref }}"
    method: DELETE
    force_basic_auth: yes
    user: "{{infoblox_username}}"
    password: "{{infoblox_password}}"
    validate_certs: no