---
- name: Infoblox - Get A record ID
  connection: local
  uri:
    url: "{{infoblox_url}}/record:{{infoblox_recordtype}}"
    method: GET
    force_basic_auth: yes
    user: "{{infoblox_username}}"
    password: "{{infoblox_password}}"
    body: "name={{ infoblox_name }}"
    return_content: yes
    validate_certs: no
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: infoblox_read_id 

- debug: msg="Name {{ infoblox_read_id.json[0].name }} - ipv4addr {{ infoblox_read_id.json[0].ipv4addr }} - Id {{ infoblox_read_id.json[0]._ref }}"