---
- name: Infoblox - Get HOST record ID
  connection: local
  uri:
    url: "{{infoblox_url}}/record:{{infoblox_recordtype}}"
    method: GET
    force_basic_auth: yes
    user: "{{infoblox_username}}"
    password: "{{infoblox_password}}"
    body: "name={{ infoblox_name }}"
    return_content: yes
    validate_certs: no
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: infoblox_ptr_id 
