---
- name: Infoblox - Get PTR record ID
  connection: local
  uri:
    url: "{{infoblox_url}}/record:{{infoblox_recordtype}}"
    method: GET
    force_basic_auth: yes
    user: "{{infoblox_username}}"
    password: "{{infoblox_password}}"
    body: "ptrdname={{ infoblox_name }}"
    return_content: yes
    validate_certs: no
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: infoblox_delete_id_ptr

- name: Infoblox - Delete PTR record
  connection: local
  uri:
    url: "{{infoblox_url}}/{{ infoblox_delete_id_ptr.json[0]._ref }}"
    method: DELETE
    force_basic_auth: yes
    user: "{{infoblox_username}}"
    password: "{{infoblox_password}}"
    validate_certs: no